#pragma config(Motor,  port2,           drive,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void bobby ()
{
if (vexRT[Btn6U]== 1)
	{
		motor[port2] = 100;
	}
	else if (vexRT[Btn6D] == 1)
	{
		motor[port2] = -100;
	}
		else
	{
		motor[port2] = 0;
	}
}







task main()
{
	while(1)
	{
		bobby ();
	}


}
