#pragma config(Motor,  port2,           Collection,            tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void collection_system ()

{
	if (vexRT[Btn6U] == 1)
	{
		motor[port2] = 128;
	}
	else if (vexRT[Btn6D] == 1)
	{
		motor[port2] = -127;
	}
	else
	{
		motor[port2] = 0;
	}
}
//cool
task main()
{
	motor[port2] = 128;
	while (1)
	{
		collection_system ();
	}

}
