#pragma config(Motor,  port2,           EE,            tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void ee ()
	//int collection;
{
	if (vexRT[Btn8L] == 1)
	{
		motor[port2] = 127;
	}
	else if (vexRT[Btn8R] == 1)
	{
		motor[port2] = -127;
	}
	//else
	//{
		//motor[port2] = -127 ;
	//}
}

//we thought of something butt we AREN'T THAT SMART BRUH!!!!
task main()
{
	motor[port2] = -127;
	while (1) {
	   ee ();
	}
}
