#pragma config(Motor,  port5,           gaurangtest,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//programing is cunfusing
void motor_test ()
{
if (vexRT[Btn5U] ==1)
{

	motor[port5]=100;
	}
	else if (vexRT[Btn5D] ==1)
{
	motor[port5]=-100;
}
	else
{
	motor[port5]=0;
}
}


task main()
{
while(1)
{
motor_test ()	;
}


}
