#pragma config(Motor,  port2,           rightwheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           endeffector,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           Collection,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           leftwheel,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define MAX_SPEED 100
 void drive()  //We are trying to drive the robot
 {
   int forward_drive;
   motor[port2] = vexRT[Ch2];
   motor[port9] = vexRT[Ch3];
 if (forward_drive == 1)
	forward_drive=1;
	else
		forward_drive=0;
}

	void arm_motor() //trying to move the arm
	{

	 if (vexRT[Btn7U] == 1)
	{
motor[port4] = MAX_SPEED;
   }
	   else if (vexRT[Btn7D] == 1)
	 {
	   motor[port4] = -MAX_SPEED;
	 }
	 else
	 {
	   motor[port4] = 0;
	 }

}
void collection_system () //trying to move collection servo

{
	if (vexRT[Btn6U] == 1)
	{
		motor[port6] = 90;
	}
	else if (vexRT[Btn6D] == 1)
	{
		motor[port6] = -90;
	}
	else
	{
		motor[port6] = -90 ;
	}
}
void EE ()

{
	if (vexRT[Btn8L] == 1)
	{
		motor[port5] = 127;
	}
	else if (vexRT[Btn8R] == 1)
	{
		motor[port5] = -127;
	}
	else
	{
	//	motor[port5] = -127 ;
	}
}

	task main()
{

 	while (1)
 	{
 		arm_motor();
 		drive();
 		collection_system();
		EE ();
 		}
 }
