#pragma config(Motor,  port2,           VTest,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void collection ()
{
	if (vexRT[Btn6U] == 1)
{
	motor[port2]= 100;
}
	else if (vexRT[Btn6D] == 1)
{
	motor[port2]= -100;
}
	else
{
	motor[port1]= 0;
}
}
// Luana was here at 10 am Saturday October 15, 2016.
task main()
{
 while (1)
{
	collection();
}


}
