#pragma config(Motor,  port2,           rightwheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           secondarm,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           endeffector,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           Collection,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           Lettuce_collecter, tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           leftwheel,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MAX_SPEED 125 // Set the maximum moter speed to 125
void drive()  //We are trying to drive the robot
{
	int forward_drive;
	motor[port2] = vexRT[Ch2];	//Set Ch2 to drive the robot
	motor[port9] = vexRT[Ch3]; //Set Ch3 to drive the robot
	if (forward_drive == 1)
		forward_drive=1;
	else
		forward_drive=0;
}

void arm_motor() //trying to move the arm
{
	if (vexRT[Btn6U] == 1)// If the button 6U is pressed set the motor to max speed
	{
		motor[port4] = MAX_SPEED;
		motor[port3] = -MAX_SPEED;
	}
	else if (vexRT[Btn6D] == 1) //If the button 6D is pressed then set the motor to the opposite max speed.
	{
		motor[port4] = -MAX_SPEED;
		motor[port3] = MAX_SPEED;
	}
	else
	{
		motor[port4] = 0; //If not keep the motor at 0
	}
}

void collection_system () //trying to move collection servo

{
	if (vexRT[Btn7U] == 1) // If button 7U is pressed then move the Collection ball drop to the right
	{
		motor[port6] = 90;
	}
	else if (vexRT[Btn7D] == 1) // If button 7D is pressed then move the Collection ball drop to the left.
	{
		motor[port6] = -90;
	}
	else										//Even if none of those are pushed keep or move the motor to the left to make it ready to do a full 90 degree rotation
	{
		motor[port6] = -90 ;
	}
}

void EE () //
{
	if (vexRT[Btn8L] == 1)
	{
		motor[port5] = 127;
	}
	else if (vexRT[Btn8R] == 1)
	{
		motor[port5] = -127;
	}
}

void lettuce_ee_collecter ()

{
	if (vexRT[Btn5U] == 1)
	{
		motor[port7] = 127;
	}
	else if (vexRT[Btn5D] == 1)
	{
		motor[port7] = -127;
	}
	else
	{
		motor[port7] = -127 ;
	}
}

task main()
{
	motor[port5] = -127 ;
	while (1)
	{
		arm_motor();
		drive();
		collection_system();
		EE ();
		lettuce_ee_collecter();
	}
}
